import i18n from 'i18next'
import { initReactI18next } from 'react-i18next'

const resources = {
  zh: {
    translation: {
      nav: { overview: '概览', nodes: '加速节点', nodesShort: '节点', cache: '缓存', domain: '域名加速', domainShort: '转换', imageTools: '镜像工具', imageToolsShort: '工具', settings: '设置与部署', settingsShort: '设置' },
      shell: { skip: '跳到主要内容', mainNav: '主导航', mobileNav: '移动端主导航', connected: '服务已连接', registryHealthy: 'Registry v2 正常', light: '切换到浅色主题', dark: '切换到暗色主题', language: 'Switch to English' },
      login: { title: '登录', description: '登录以管理这个 Donkey 实例。', username: '用户名', password: '密码', submit: '登录', invalid: '用户名或密码不正确。', rateLimited: '尝试次数过多，请稍后再试。', configFailed: '无法读取登录配置。', oidcFailed: '单点登录未完成，请重试。', or: '或者', continueWith: '使用 {{provider}} 登录', notConfigured: '尚未配置登录方式，请设置管理员或 OIDC 环境变量。', admin: '管理员', member: '成员', logout: '退出登录' },
      common: { loading: '正在读取状态', retry: '重试', cancel: '取消', save: '保存', delete: '删除', edit: '编辑', enabled: '启用', disabled: '停用', online: '在线', error: '异常', configured: '已配置', copy: '复制', copied: '已复制', noData: '暂无数据' },
      errors: { loadTitle: '暂时无法读取数据', generic: '请求失败' },
      dashboard: { title: '运行概览', description: '节点、缓存和调度状态。每 15 秒刷新。', online: '服务在线', waiting: '等待节点', healthyNodes: '健康节点', activeRouting: '参与当前调度', cacheSize: '缓存容量', objects: '{{count}} 个内容对象', hits: '累计命中', hitsDetail: '减少上游重复下载', mode: '调度模式', concurrent: '多源并发', fallback: '单源回退', integrity: '完整性校验已启用', throughput: '节点测量吞吐', throughputDesc: '最近一次测量的平滑速度，单位 KB/s', speed: '测量速度', chartEmpty: '添加节点后显示测量结果', currentRoute: '当前路由', routeDesc: '按综合分数排序，失败时切换节点', available: '可用' },
      nodes: { title: '加速节点', description: '管理 Registry、镜像和代理节点。排序依据为吞吐、延迟、成功率和优先级。', add: '添加节点', all: '全部', dockerhub: 'Docker Hub', ghcr: 'GHCR', registry: 'Registry', domain: '域名', proxy: '代理', emptyTitle: '这个分类还没有节点', emptyDesc: '添加上游后会检查 Registry v2 支持情况。', reading: '正在读取节点', probe: '立即测速', edit: '编辑节点', currentRate: '当前速率', measuredRate: '测量速率', latency: '延迟', downloaded: '累计下载', successRate: '成功率 {{value}}% · 调度分 {{score}}', measured: '测量完成', measuredMessage: '{{name}} 的状态已更新', measureFailed: '测量失败', createTitle: '添加加速节点', editTitle: '编辑加速节点', name: '节点名称', namePlaceholder: '1ms Docker', type: '节点类型', upstream: '上游地址', upstreamDesc: '填写 Registry 根地址。默认只允许公开 HTTPS 地址。', routePrefix: 'Registry 路由前缀', routePrefixDesc: '例如 ghcr。拉取 donkey/ghcr/org/image 时只使用该组节点。', priority: '优先级', priorityDesc: '数值越小越优先', connectIp: '优选连接 IP', connectIpDesc: '覆盖 DNS，保留 TLS SNI', optional: '可选', enableNode: '启用节点', cfip: '标记为 CFIP 优选', upstreamAuth: '上游认证', authMode: '认证方式', authNone: '无需认证', authBasic: 'Docker / HTTP Basic', authBearer: 'Bearer Token', authHeader: '自定义 Header', username: '用户名', oneMsUser: '1ms 付费节点的用户名为 1ms', headerName: 'Header 名称', newSecret: '新密钥（留空保持不变）', secret: '认证密钥', secretDesc: '使用 DONKEY_CREDENTIAL_KEY 加密后存入 SQLite，保存后不再回显', saveNode: '保存节点', created: '节点已添加', updated: '节点已更新', savedMessage: '节点配置已生效', saveFailed: '无法保存节点', deleted: '节点已删除', deleteFailed: '无法删除节点', validationName: '请输入节点名称', validationUrl: '请输入完整的 HTTP(S) URL', validationUsername: 'Basic 认证需要用户名', validationHeader: '请输入 Header 名称', validationSecret: '请输入认证密钥' },
      cache: { title: '缓存管理', description: '内容寻址的 Blob 缓存支持 Range 响应、授权隔离与安全淘汰。正在传输的对象不会被回收。', used: '已使用', capacity: '容量上限', policy: '淘汰策略', watermarks: '回收水位', ttl: '过期时间', forever: '不过期', objects: '缓存对象', emptyTitle: '缓存还是空的', emptyDesc: '第一次通过 Donkey 拉取 Blob 后，它会出现在这里。', digest: 'Digest / Key', size: '大小', hits: '命中', lastAccess: '最后访问', remove: '移除缓存', removed: '缓存已移除', removeFailed: '无法移除缓存', confirmDeleteTitle: '确认移除缓存', confirmDeleteMessage: '此操作会删除本地 Blob；下次请求时需要重新从上游下载。', balanced: '平衡', lru: '最近最少使用', lfu: '最不常使用' },
      domain: { title: '域名加速', description: '将已配置域名的下载地址转换为加速地址。不匹配的域名会被拒绝。', convertTitle: '转换下载链接', original: '原始链接', convert: '生成加速链接', result: '加速链接', open: '打开链接', mappings: '域名映射', add: '添加映射', sourceHost: '源域名', upstreamBase: '上游根地址', publicBase: '公开加速地址', emptyTitle: '还没有域名映射', emptyDesc: '添加 GitHub、Apache 或其他下载站点的映射。', created: '映射已添加', updated: '映射已更新', deleted: '映射已删除', saveFailed: '无法保存映射', convertFailed: '无法转换链接' },
      imageTools: { title: '镜像工具', description: '浏览镜像内容、生成离线包、复制到其他 Registry，并创建定时同步规则。', content: '内容浏览', export: '离线导出', copy: 'Registry 复制', schedules: '同步规则', tasks: '任务记录', source: '源镜像', pullVia: '拉取方式', direct: '直连源 Registry', sourceRouteHint: '源站不可达时，可选择已配置且带独立认证的加速节点。', sourceAuthNone: '公开源 / 无需认证', platform: '平台', startExtract: '提取文件树', startExport: '创建导出任务', startCopy: '确认并复制', outputFormat: '离线包格式', dockerArchive: 'Docker archive', ociArchive: 'OCI archive', destination: '目标镜像引用', destinationCredential: '目标 Registry 凭据', sourceCredential: '源 Registry 凭据', credentials: 'Registry 凭据', addCredential: '添加凭据', credentialName: '凭据名称', registry: 'Registry 地址', authMode: '认证方式', username: '用户名', secret: '密码 / Access Token', secretHint: '提交后加密保存，不再回显', createRule: '创建同步规则', ruleName: '规则名称', cron: 'Cron（秒 分 时 日 月 周）', timezone: '时区', nextRun: '下次运行', runNow: '立即运行', noRules: '还没有同步规则', noTasks: '还没有镜像任务', stage: '阶段', progress: '进度', download: '下载离线包', browse: '浏览文件', cancel: '取消任务', retry: '重试', confirmCopy: '我确认目标引用和凭据正确，允许 Donkey 向目标 Registry 写入。', queued: '任务已创建', credentialSaved: '凭据已保存', failed: '操作失败', root: '根目录', parent: '上一级', emptyFiles: '目录为空', fileDownload: '下载文件', credentialRequired: '请先添加目标 Registry 凭据' },
      settings: { title: '设置与部署', description: '这些参数由环境变量控制，页面只读展示实际生效值，避免 UI 与容器配置漂移。', endpoints: '监听端点', admin: '管理 / CONNECT', registry: 'Registry', tls: 'TLS', enabled: '已启用', disabled: '未启用', scheduler: '并发调度', schedulerPolicy: '节点策略', balancedPolicy: '综合评分', speedFirstPolicy: '速度优先', chunk: '分片大小', concurrency: '并发数', threshold: '并发阈值', cache: '缓存策略', private: '私网节点', allowed: '允许', denied: '拒绝', adminTransport: '管理凭据传输', transportTls: 'HTTPS', transportLoopback: '宿主 loopback', transportInsecure: '不安全', dockerConfig: 'Docker daemon 配置', composeHint: '生产环境请为 Registry 配置 TLS，并使用 docker login 登录 Donkey。', command: '登录命令' }
    },
  },
  en: {
    translation: {
      nav: { overview: 'Overview', nodes: 'Upstreams', nodesShort: 'Nodes', cache: 'Cache', domain: 'DomainFold', domainShort: 'Convert', imageTools: 'Image tools', imageToolsShort: 'Tools', settings: 'Settings & deploy', settingsShort: 'Settings' },
      shell: { skip: 'Skip to main content', mainNav: 'Main navigation', mobileNav: 'Mobile navigation', connected: 'Service connected', registryHealthy: 'Registry v2 healthy', light: 'Switch to light theme', dark: 'Switch to dark theme', language: '切换到中文' },
      login: { title: 'Sign in', description: 'Sign in to manage this Donkey instance.', username: 'Username', password: 'Password', submit: 'Sign in', invalid: 'The username or password is incorrect.', rateLimited: 'Too many attempts. Try again later.', configFailed: 'Unable to load sign-in configuration.', oidcFailed: 'Single sign-on did not complete. Try again.', or: 'or', continueWith: 'Continue with {{provider}}', notConfigured: 'No sign-in method is configured. Set the administrator or OIDC environment variables.', admin: 'Administrator', member: 'Member', logout: 'Sign out' },
      common: { loading: 'Loading status', retry: 'Retry', cancel: 'Cancel', save: 'Save', delete: 'Delete', edit: 'Edit', enabled: 'Enabled', disabled: 'Disabled', online: 'Online', error: 'Error', configured: 'Configured', copy: 'Copy', copied: 'Copied', noData: 'No data' },
      errors: { loadTitle: 'Unable to load data', generic: 'Request failed' },
      dashboard: { title: 'Runtime overview', description: 'Node, cache, and scheduler status. Refreshes every 15 seconds.', online: 'Service online', waiting: 'Waiting for nodes', healthyNodes: 'Healthy nodes', activeRouting: 'In active routing', cacheSize: 'Cache size', objects: '{{count}} content objects', hits: 'Cache hits', hitsDetail: 'Repeated upstream downloads reduced', mode: 'Scheduling mode', concurrent: 'Multi-source', fallback: 'Single-source', integrity: 'Integrity checks enabled', throughput: 'Measured throughput', throughputDesc: 'Smoothed speed from the latest probe, in KB/s', speed: 'Measured speed', chartEmpty: 'Add a node to see measurements', currentRoute: 'Current route', routeDesc: 'Ranked by score; switches nodes on failure', available: 'Ready' },
      nodes: { title: 'Acceleration nodes', description: 'Manage Registry, mirror, and proxy nodes. Ranking uses throughput, latency, success rate, and priority.', add: 'Add node', all: 'All', dockerhub: 'Docker Hub', ghcr: 'GHCR', registry: 'Registry', domain: 'Domain', proxy: 'Proxy', emptyTitle: 'No nodes in this category', emptyDesc: 'Registry v2 support is checked after an upstream is added.', reading: 'Loading nodes', probe: 'Probe now', edit: 'Edit node', currentRate: 'Current rate', measuredRate: 'Measured rate', latency: 'Latency', downloaded: 'Downloaded', successRate: '{{value}}% success · score {{score}}', measured: 'Probe complete', measuredMessage: '{{name}} status was updated', measureFailed: 'Probe failed', createTitle: 'Add acceleration node', editTitle: 'Edit acceleration node', name: 'Node name', namePlaceholder: '1ms Docker', type: 'Node type', upstream: 'Upstream URL', upstreamDesc: 'Enter the Registry root URL. Public HTTPS addresses are required by default.', routePrefix: 'Registry route prefix', routePrefixDesc: 'For example ghcr. donkey/ghcr/org/image uses only this node group.', priority: 'Priority', priorityDesc: 'Lower values are preferred', connectIp: 'Preferred connect IP', connectIpDesc: 'Overrides DNS while preserving TLS SNI', optional: 'Optional', enableNode: 'Enable node', cfip: 'Mark as CFIP preferred', upstreamAuth: 'Upstream authentication', authMode: 'Authentication mode', authNone: 'No authentication', authBasic: 'Docker / HTTP Basic', authBearer: 'Bearer token', authHeader: 'Custom header', username: 'Username', oneMsUser: 'The 1ms paid-node username is 1ms', headerName: 'Header name', newSecret: 'New secret (blank keeps current)', secret: 'Authentication secret', secretDesc: 'Encrypted with DONKEY_CREDENTIAL_KEY before SQLite storage and never returned', saveNode: 'Save node', created: 'Node added', updated: 'Node updated', savedMessage: 'Node configuration is active', saveFailed: 'Unable to save node', deleted: 'Node deleted', deleteFailed: 'Unable to delete node', validationName: 'Enter a node name', validationUrl: 'Enter a complete HTTP(S) URL', validationUsername: 'Basic authentication needs a username', validationHeader: 'Enter a header name', validationSecret: 'Enter an authentication secret' },
      cache: { title: 'Cache management', description: 'Content-addressed Blob caching with Range responses, authorization scopes, and safe eviction. In-flight objects are protected.', used: 'Used', capacity: 'Capacity', policy: 'Eviction policy', watermarks: 'Watermarks', ttl: 'Expiration', forever: 'Never', objects: 'Cached objects', emptyTitle: 'The cache is empty', emptyDesc: 'Blobs appear here after the first pull through Donkey.', digest: 'Digest / Key', size: 'Size', hits: 'Hits', lastAccess: 'Last access', remove: 'Remove cache entry', removed: 'Cache entry removed', removeFailed: 'Unable to remove cache entry', confirmDeleteTitle: 'Remove cached Blob?', confirmDeleteMessage: 'This deletes the local Blob. Donkey will download it from an upstream again when requested.', balanced: 'Balanced', lru: 'Least recently used', lfu: 'Least frequently used' },
      domain: { title: 'Domain acceleration', description: 'Convert downloads for configured domains. Requests for unmatched domains are rejected.', convertTitle: 'Convert download URL', original: 'Original URL', convert: 'Create accelerated URL', result: 'Accelerated URL', open: 'Open URL', mappings: 'Domain mappings', add: 'Add mapping', sourceHost: 'Source host', upstreamBase: 'Upstream base', publicBase: 'Public acceleration URL', emptyTitle: 'No domain mappings', emptyDesc: 'Add mappings for GitHub, Apache, or other download sites.', created: 'Mapping added', updated: 'Mapping updated', deleted: 'Mapping deleted', saveFailed: 'Unable to save mapping', convertFailed: 'Unable to convert URL' },
      imageTools: { title: 'Image tools', description: 'Browse image contents, create offline archives, copy to another Registry, and schedule synchronization.', content: 'Content', export: 'Offline export', copy: 'Registry copy', schedules: 'Sync rules', tasks: 'Tasks', source: 'Source image', pullVia: 'Pull through', direct: 'Direct source Registry', sourceRouteHint: 'Select an authenticated acceleration node when the source Registry is unreachable directly.', sourceAuthNone: 'Public source / no credential', platform: 'Platform', startExtract: 'Extract file tree', startExport: 'Create export job', startCopy: 'Confirm and copy', outputFormat: 'Archive format', dockerArchive: 'Docker archive', ociArchive: 'OCI archive', destination: 'Destination image reference', destinationCredential: 'Destination Registry credential', sourceCredential: 'Source Registry credential', credentials: 'Registry credentials', addCredential: 'Add credential', credentialName: 'Credential name', registry: 'Registry address', authMode: 'Authentication mode', username: 'Username', secret: 'Password / access token', secretHint: 'Encrypted on submit and never returned', createRule: 'Create sync rule', ruleName: 'Rule name', cron: 'Cron (sec min hour day month weekday)', timezone: 'Timezone', nextRun: 'Next run', runNow: 'Run now', noRules: 'No sync rules', noTasks: 'No image tasks', stage: 'Stage', progress: 'Progress', download: 'Download archive', browse: 'Browse files', cancel: 'Cancel job', retry: 'Retry', confirmCopy: 'I confirm the destination reference and credential and allow Donkey to write to the target Registry.', queued: 'Job created', credentialSaved: 'Credential saved', failed: 'Operation failed', root: 'Root', parent: 'Parent', emptyFiles: 'This directory is empty', fileDownload: 'Download file', credentialRequired: 'Add a destination Registry credential first' },
      settings: { title: 'Settings & deployment', description: 'Environment variables control these read-only values so the UI never drifts from container configuration.', endpoints: 'Listen endpoints', admin: 'Admin / CONNECT', registry: 'Registry', tls: 'TLS', enabled: 'Enabled', disabled: 'Disabled', scheduler: 'Concurrent scheduler', schedulerPolicy: 'Node policy', balancedPolicy: 'Composite score', speedFirstPolicy: 'Speed first', chunk: 'Chunk size', concurrency: 'Concurrency', threshold: 'Parallel threshold', cache: 'Cache policy', private: 'Private nodes', allowed: 'Allowed', denied: 'Denied', adminTransport: 'Admin credential transport', transportTls: 'HTTPS', transportLoopback: 'Host loopback', transportInsecure: 'Insecure', dockerConfig: 'Docker daemon configuration', composeHint: 'Configure Registry TLS in production and use docker login to authenticate with Donkey.', command: 'Login command' }
    },
  },
} as const

const initialLanguage = localStorage.getItem('donkey-language') ?? (navigator.language.startsWith('zh') ? 'zh' : 'en')
document.documentElement.lang = initialLanguage === 'zh' ? 'zh-CN' : 'en'

void i18n.use(initReactI18next).init({
  resources,
  lng: initialLanguage,
  fallbackLng: 'en',
  interpolation: { escapeValue: false },
})

i18n.on('languageChanged', (language) => {
  localStorage.setItem('donkey-language', language)
  document.documentElement.lang = language === 'zh' ? 'zh-CN' : 'en'
})

export default i18n
